- hosts: vm
  tasks:
  - name: Ansible copy receive.py file to remote server
    copy:
      src: ./resource/receive.py
      dest: ~/
  - name: Ansible copy start.py file to remote server
    copy:
      src: ./resource/start.py
      dest: ~/
  - name: Ansible copy send.py file to remote server
    copy:
      src: ./resource/send.py
      dest: ~/