- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: magicButtonResourceGroup
      name: magicButtonVM
      vm_size: Standard_B2s
      admin_username: "{{ lookup('env','admin_username') }}"
      admin_password: "{{ lookup('env','admin_password') }}"
      network_interfaces: myNIC
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: "18.04-LTS"
        version: latest